---
- name: test out community.general.mail
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Example playbook sending mail to root
      community.general.mail:
        host: mail
        port: 25
        subject: Test community.general mail from {{ ansible_hostname }}
