---
- name: test out community.general.mail
  hosts: all

  tasks:
  - name: Example playbook sending mail to root
    community.general.mail:
      subject: Test from Community General Mail Module
      secure: never
    delegate_to: localhost
